# railway.toml
[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-spa poppler-utils && pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT app:app"
healthcheckPath = "/api/check-ocr"
